### ISSUE TITLE
The 'aleph' distribution was not found and is required by the application

### ISSUE THREAD

**Issue by snakonechny** [pudo/aleph#125]
I'm running into a strange error when initializing the DB. This happens consistently on OSX and Ubuntu, within a virtualenv and outside one. The error is below:

```
aleph# aleph init
Traceback (most recent call last):
  File "/usr/local/bin/aleph", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3019, in <module>
    @_call_aside
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3003, in _call_aside
    f(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3032, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 655, in _build_master
    ws.require(__requires__)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 963, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 849, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'aleph' distribution was not found and is required by the application
```

<details>
  <summary>My docker-compose file</summary>

``` yml
version: "2"

services:

  resolvable:
    image: mgood/resolvable
    volumes:
      - "/var/run/docker.sock:/tmp/docker.sock"
      - "/etc/resolv.conf:/tmp/resolv.conf"

  postgres:
    image: postgres:9.4
    volumes:
      - "./build/data/postgres:/var/lib/postgresql/data"
      - "./build/logs/postgres:/var/log"
    environment:
      POSTGRES_USER:     aleph
      POSTGRES_PASSWORD: aleph
      POSTGRES_DATABASE: aleph
    ports:
     - "127.0.0.1:5439:5432"

  elasticsearch:
    image: elasticsearch:2.2.0
    volumes:
      - "./build/data/elasticsearch:/usr/share/elasticsearch/data"
      - "./build/logs/elasticsearch:/var/log"
    ports:
      - "127.0.0.1:9201:9209"

  rabbitmq:
    image: rabbitmq
    volumes:
      - "./build/data/rabbitmq:/var/lib/rabbitmq"
      - "./build/logs/rabbitmq:/var/log"
    ports:
      - 5672

  worker:
      image: pudo/aleph:latest
      command: make worker
      links:
        - postgres
        - elasticsearch
        - rabbitmq
      volumes:
        - "./build/logs/worker:/var/log"
        - "./build/archive:/data"
        - "./build/polyglot:/polyglot"
        - "./:/aleph"
      environment:
        C_FORCE_ROOT: 'true'
        ALEPH_ELASTICSEARCH_URI: http://elasticsearch:9200/
        ALEPH_DATABASE_URI: postgresql://aleph:aleph@postgres/aleph
        ALEPH_BROKER_URI: amqp://guest:guest@rabbitmq:5672
        POLYGLOT_DATA_PATH: /polyglot
      env_file:
        - aleph.env

  beat:
      image: pudo/aleph:latest
      command: make beat
      links:
        - postgres
        - elasticsearch
        - rabbitmq
      volumes:
        - "./build/logs/beat:/var/log"
        - "./build/data/beat:/var/lib/"
        - "./build/archive:/data"
        - "./build/polyglot:/polyglot"
        - "./:/aleph"
      environment:
        C_FORCE_ROOT: 'true'
        ALEPH_ELASTICSEARCH_URI: http://elasticsearch:9200/
        ALEPH_DATABASE_URI: postgresql://aleph:aleph@postgres/aleph
        ALEPH_BROKER_URI: amqp://guest:guest@rabbitmq:5672
        POLYGLOT_DATA_PATH: /polyglot
      env_file:
        - aleph.env

  app:
      image: pudo/aleph:latest
      command: make web
      ports:
        - "13376:8000"
      links:
        - postgres
        - elasticsearch
        - rabbitmq
      volumes:
        - "./build/logs/web:/var/log"
        - "./build/archive:/data"
        - "./build/polyglot:/polyglot"
        - "./:/aleph"
      environment:
        C_FORCE_ROOT: 'true'
        ALEPH_ELASTICSEARCH_URI: http://elasticsearch:9200/
        ALEPH_DATABASE_URI: postgresql://aleph:aleph@postgres/aleph
        ALEPH_BROKER_URI: amqp://guest:guest@rabbitmq:5672
        POLYGLOT_DATA_PATH: /polyglot
      env_file:
        - aleph.env
```
</summary></details>

This is almost certainly something silly I'm missing. Thanks a ton for the help and for this great tool!

**Comment by pudo** [comment]
That's a very weird error, it almost sounds like the pip install is damaged somehow. I'm a tiny bit confused by your description: did you try to set it up on OS X raw, or also run it within docker? If it's within docker, perhaps you could do me a favour and see if the problem persists if you just run ``pip install --upgrade -e /aleph`` one extra time. We've been messing with the Dockerfiles a bit lately and there might be fallout, and our local deployment routine does a small layer on top of ``pudo/aleph:latest`` (otherwise that's pretty much what's running on data.occrp.org).

**Comment by stas** [comment]
Hey @snakonechny, there's a similar report related to the installation procedure at #126 

Could you please confirm the issue after removing any old containers and images and running a fresh build following the docs we recently updated?
http://aleph.readthedocs.io/en/latest/installation.html#development-installation-steps

**Comment by snakonechny** [comment]
@pudo, I tried both - a raw OS X install and an internalized Docker install. Same error in both environments.

@stas, I will be away from this for a week or so, but as soon as I'm back I'll try out the updated steps.

Thanks for your quick response!

**Comment by pudo** [comment]
Thanks, @stas, for your input! I just pulled ``pudo/aleph:latest`` and could not reproduce this error immediately.

**Comment by snakonechny** [comment]
Hi @stas ,
I purged my Docker installation/images/containers and followed the instruction [outlined here](http://aleph.readthedocs.io/en/latest/installation.html#development-installation-steps). The error I get is different this time around, though I think this is the same flavor of pip/package install problems:

```
docker-compose run app python aleph/manage.py init -s analyzers
Starting aleph_postgres_1
Starting aleph_rabbitmq_1
Starting aleph_elasticsearch_1
Traceback (most recent call last):
  File "aleph/manage.py", line 8, in <module>
    from aleph.core import create_app, archive, datasets
  File "/aleph/aleph/__init__.py", line 4, in <module>
    import requests
  File "/usr/local/lib/python2.7/dist-packages/requests/__init__.py", line 60, in <module>
    from .packages.urllib3.exceptions import DependencyWarning
  File "/usr/local/lib/python2.7/dist-packages/requests/packages/__init__.py", line 29, in <module>
    import urllib3
  File "/usr/lib/python2.7/dist-packages/urllib3/__init__.py", line 10, in <module>
    from .connectionpool import (
  File "/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 12, in <module>
    from Queue import LifoQueue, Empty, Full
  File "/aleph/aleph/Queue.py", line 1, in <module>
    from aleph.core import create_app, celery as app  # noqa
  File "/aleph/aleph/core.py", line 11, in <module>
    from kombu import Queue
  File "/usr/local/lib/python2.7/dist-packages/kombu/__init__.py", line 81, in __getattr__
    module = __import__(object_origins[name], None, None, [name])
  File "/usr/local/lib/python2.7/dist-packages/kombu/entity.py", line 6, in <module>
    from .abstract import MaybeChannelBound, Object
  File "/usr/local/lib/python2.7/dist-packages/kombu/abstract.py", line 6, in <module>
    from .connection import maybe_channel
  File "/usr/local/lib/python2.7/dist-packages/kombu/connection.py", line 15, in <module>
    from kombu import exceptions
  File "/usr/local/lib/python2.7/dist-packages/kombu/exceptions.py", line 6, in <module>
    from amqp import ChannelError, ConnectionError, ResourceError
  File "/usr/local/lib/python2.7/dist-packages/amqp/__init__.py", line 45, in <module>
    from .basic_message import Message  # noqa
  File "/usr/local/lib/python2.7/dist-packages/amqp/basic_message.py", line 29, in <module>
    from .serialization import GenericContent
  File "/usr/local/lib/python2.7/dist-packages/amqp/serialization.py", line 31, in <module>
    from .exceptions import FrameSyntaxError
  File "/usr/local/lib/python2.7/dist-packages/amqp/exceptions.py", line 18, in <module>
    from .five import python_2_unicode_compatible
  File "/usr/local/lib/python2.7/dist-packages/amqp/five.py", line 6, in <module>
    import vine.five
  File "/usr/local/lib/python2.7/dist-packages/vine/__init__.py", line 8, in <module>
    from .abstract import Thenable
  File "/usr/local/lib/python2.7/dist-packages/vine/abstract.py", line 8, in <module>
    from .five import with_metaclass
  File "/usr/local/lib/python2.7/dist-packages/vine/five.py", line 181, in <module>
    from Queue import Queue, Empty, Full, LifoQueue  # noqa
ImportError: cannot import name Queue
```

As a side note, @pudo , `pip install --upgrade -e /aleph` did fix the original error I was seeing. However, I kept on running into other package installation errors (including `ImportError: cannot import name Queue`)

**Comment by stas** [comment]
Oh, I'll take a look. Thanks and sorry for all the trouble @snakonechny :sweat:

**Comment by pudo** [comment]
This looks like an ultra-weird naming conflict that I haven't stumbled upon before. It seems like urllib3 tries to load `Queue` and ends up loading the relevant aleph module instead. Wonder if renaming that is the wisest move here.

**Comment by pudo** [comment]
@snakonechny any chance you can give this a shot? It's still incredibly odd this wouldn't happen to me when building the docker.

**Comment by snakonechny** [comment]
@pudo , thanks for your prompt response and for your patience with this!

I'm no longer seeing either of the errors above. I'm also able to run `docker-compose up -d` and get the following back:
```
Starting aleph_rabbitmq_1
aleph_resolvable_1 is up-to-date
Starting aleph_elasticsearch_1
Starting aleph_postgres_1
Starting aleph_app_1
Starting aleph_worker_1
Starting aleph_beat_1
```
No errors there. All images come up correctly:
```
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
pudo/aleph          latest              8cebb3cb9eb8        25 minutes ago      2.477 GB
rabbitmq            latest              ec798eba2c56        45 hours ago        179 MB
postgres            9.4                 96c39c9be38e        45 hours ago        264.9 MB
elasticsearch       2.2.0               213e5061cbe1        10 months ago       346.6 MB
mgood/resolvable    latest              93d6a0d32c40        19 months ago       16.19 MB
```

Then this gets interesting again. I run `docker-compose run app python aleph/manage.py init -s analyzers` as prescribed. This is what comes back:

```
Starting aleph_postgres_1
Starting aleph_rabbitmq_1
Starting aleph_elasticsearch_1
INFO:aleph.model:Beginning database migration...
Traceback (most recent call last):
  File "aleph/manage.py", line 220, in <module>
    main()
  File "aleph/manage.py", line 216, in main
    manager.run()
  File "/usr/local/lib/python2.7/dist-packages/flask_script/__init__.py", line 412, in run
    result = self.handle(sys.argv[0], sys.argv[1:])
  File "/usr/local/lib/python2.7/dist-packages/flask_script/__init__.py", line 383, in handle
    res = handle(*args, **config)
  File "/usr/local/lib/python2.7/dist-packages/flask_script/commands.py", line 216, in __call__
    return self.run(*args, **kwargs)
  File "aleph/manage.py", line 163, in init
    upgrade_db()
  File "/aleph/aleph/model/__init__.py", line 23, in upgrade_db
    flask_migrate.upgrade()
  File "/usr/local/lib/python2.7/dist-packages/flask_migrate/__init__.py", line 235, in upgrade
    command.upgrade(config, revision, sql=sql, tag=tag)
  File "/usr/local/lib/python2.7/dist-packages/alembic/command.py", line 174, in upgrade
    script.run_env()
  File "/usr/local/lib/python2.7/dist-packages/alembic/script/base.py", line 397, in run_env
    util.load_python_file(self.dir, 'env.py')
  File "/usr/local/lib/python2.7/dist-packages/alembic/util/pyfiles.py", line 93, in load_python_file
    module = load_module_py(module_id, path)
  File "/usr/local/lib/python2.7/dist-packages/alembic/util/compat.py", line 79, in load_module_py
    mod = imp.load_source(module_id, path, fp)
  File "/aleph/aleph/migrate/env.py", line 47, in <module>
    run_migrations_online()
  File "/aleph/aleph/migrate/env.py", line 33, in run_migrations_online
    connection = engine.connect()
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 2018, in connect
    return self._connection_cls(self, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 72, in __init__
    if connection is not None else engine.raw_connection()
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 2104, in raw_connection
    self.pool.unique_connection, _connection)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 2078, in _wrap_pool_connect
    e, dialect, self)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1405, in _handle_dbapi_exception_noconnection
    exc_info
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/util/compat.py", line 202, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 2074, in _wrap_pool_connect
    return fn()
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/pool.py", line 318, in unique_connection
    return _ConnectionFairy._checkout(self)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/pool.py", line 713, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/pool.py", line 480, in checkout
    rec = pool._do_get()
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/pool.py", line 1151, in _do_get
    return self._create_connection()
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/pool.py", line 323, in _create_connection
    return _ConnectionRecord(self)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/pool.py", line 449, in __init__
    self.connection = self.__connect()
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/pool.py", line 607, in __connect
    connection = self.__pool._invoke_creator(self)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/strategies.py", line 97, in connect
    return dialect.connect(*cargs, **cparams)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/default.py", line 385, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/usr/local/lib/python2.7/dist-packages/psycopg2/__init__.py", line 164, in connect
    conn = _connect(dsn, connection_factory=connection_factory, async=async)
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) could not translate host name "postgres" to address: Name or service not known
```
I'm running all of this inside a virtualenv. Out of curiosity, I reran it outside one, on barebones OSX and got an identical error.

Again, thanks for all your help so far!

**Comment by stas** [comment]
@snakonechny what do you mean by virtualenv? Docker installation doesn't use virtualenv.

> sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) could not translate host name "postgres" to address: Name or service not known

I've stumbled upon this previously, but somehow didn't manage to reproduce it after another installation.
Normally `postgres` hostname is provided by the Docker compose. Something is :fish:y here.

**Comment by stas** [comment]
@snakonechny I just pulled the latest Docker image using `docker-compose up` and I could not reproduce the issue. Please make sure you follow our documentation, this explains why your installation would not connect to the database (it is managed by Docker).

http://aleph.readthedocs.io/en/latest/installation.html#development-installation-steps
