### ISSUE TITLE
aleph upgrade Error on Installation

### ISSUE THREAD

**Issue by danishthanvi1** [pudo/aleph#34]
have installed aleph via docker and docker-compose. Upon running "aleph upgrade" it throws the following Error.

[root@localhost aleph]# docker-compose run worker /bin/bash
Starting aleph_elasticsearch_1
Starting aleph_postgres_1
root@58ced8c:/aleph# aleph upgrade
INFO:aleph.model:Beginning database migration...
INFO:alembic.runtime.migration:Context impl PostgresqlImpl.
INFO:alembic.runtime.migration:Will assume transactional DDL.
INFO:aleph.model:Creating system roles...
WARNING:elasticsearch:PUT /aleph/mapping/document [status:404 request:0.835s]
Traceback (most recent call last):
File "/usr/local/bin/aleph", line 9, in
load_entry_point('aleph', 'console_scripts', 'aleph')()
File "/aleph/aleph/manage.py", line 167, in main
manager.run()
File "/usr/local/lib/python2.7/site-packages/flask_script/__init_.py", line 412, in run
result = self.handle(sys.argv[0], sys.argv[1:])
File "/usr/local/lib/python2.7/site-packages/flask_script/init.py", line 383, in handle
res = handle(args, *config)
File "/usr/local/lib/python2.7/site-packages/flask_script/commands.py", line 216, in call
return self.run(args, *kwargs)
File "/aleph/aleph/manage.py", line 148, in upgrade
upgrade_search()
File "/aleph/aleph/index/admin.py", line 26, in upgrade_search
doc_type=TYPE_DOCUMENT)
File "/usr/local/lib/python2.7/site-packages/elasticsearch/client/utils.py", line 69, in _wrapped
return func(args, params=params, *kwargs)
File "/usr/local/lib/python2.7/site-packages/elasticsearch/client/indices.py", line 291, in put_mapping
'_mapping', doc_type), params=params, body=body)
File "/usr/local/lib/python2.7/site-packages/elasticsearch/transport.py", line 307, in perform_request
status, headers, data = connection.perform_request(method, url, params, body, ignore=ignore, timeout=timeout)
File "/usr/local/lib/python2.7/site-packages/elasticsearch/connection/http_urllib3.py", line 93, in perform_request
self._raise_error(response.status, raw_data)
File "/usr/local/lib/python2.7/site-packages/elasticsearch/connection/base.py", line 105, in _raise_error
raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)
elasticsearch.exceptions.NotFoundError: TransportError(404, u'index_not_found_exception')

**Comment by pudo** [comment]
Argh, seen this before. It looks like aleph isn't attempting to create the index correctly. if you have nothing in your database yet, can you please try running ``aleph evilshit`` (sorry about the name) - it'll delete and re-create both the SQL and ES indexes.

**Comment by danishthanvi1** [comment]
Yes, this is a New Installation and Database is Empty. will run this command

**Comment by danishthanvi1** [comment]
here is the result

root@58ced8c712ec:/aleph# aleph evilshit
INFO:aleph.model:Beginning database migration...
INFO:alembic.runtime.migration:Context impl PostgresqlImpl.
INFO:alembic.runtime.migration:Will assume transactional DDL.
INFO:aleph.model:Creating system roles...
Traceback (most recent call last):
  File "/usr/local/bin/aleph", line 9, in <module>
    load_entry_point('aleph', 'console_scripts', 'aleph')()
  File "/aleph/aleph/manage.py", line 167, in main
    manager.run()
  File "/usr/local/lib/python2.7/site-packages/flask_script/__init__.py", line 412, in run
    result = self.handle(sys.argv[0], sys.argv[1:])
  File "/usr/local/lib/python2.7/site-packages/flask_script/__init__.py", line 383, in handle
    res = handle(*args, **config)
  File "/usr/local/lib/python2.7/site-packages/flask_script/commands.py", line 216, in __call__
    return self.run(*args, **kwargs)
  File "/aleph/aleph/manage.py", line 161, in evilshit
    upgrade_db()
  File "/aleph/aleph/model/__init__.py", line 23, in upgrade_db
    create_system_roles()
  File "/aleph/aleph/model/__init__.py", line 28, in create_system_roles
    Role.load_or_create(Role.SYSTEM_GUEST, Role.SYSTEM, 'All visitors')
  File "/aleph/aleph/model/role.py", line 51, in load_or_create
    role = cls.by_foreign_id(foreign_id)
  File "/aleph/aleph/model/role.py", line 41, in by_foreign_id
    return cls.all().filter_by(foreign_id=foreign_id).first()
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2634, in first
    ret = list(self[0:1])
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2457, in __getitem__
    return list(res)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2736, in __iter__
    return self._execute_and_instances(context)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2751, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 914, in execute
    return meth(self, multiparams, params)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/sql/elements.py", line 323, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1010, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1146, in _execute_context
    context)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1341, in _handle_dbapi_exception
    exc_info
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 200, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1139, in _execute_context
    context)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 450, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.ProgrammingError: (psycopg2.ProgrammingError) relation "role" does not exist
LINE 2: FROM role
             ^
 [SQL: 'SELECT role.id AS role_id, role.created_at AS role_created_at, role.updated_at AS role_updated_at, role.deleted_at AS role_deleted_at, role.foreign_id AS role_foreign_id, role.name AS role_name, role.email AS role_email, role.api_key AS role_api_key, role.is_admin AS role_is_admin, role.type AS role_type \nFROM role \nWHERE role.deleted_at IS NULL AND role.foreign_id = %(foreign_id_1)s \n LIMIT %(param_1)s'] [parameters: {'foreign_id_1': 'guest', 'param_1': 1}]
root@58ced8c712ec:/aleph#

**Comment by pudo** [comment]
I've pushed a more aggressive version of evilshit. Can you give it a try?

**Comment by danishthanvi1** [comment]
Yes run the command, results i have pasted already!

**Comment by pudo** [comment]
Now I'm confused - how on earth can this happen. Which of the two errors is showing up: the role table one, or the one about the ES index? If it's the role error, can you please try deleting and re-creating the DB in postgres. If it's the ES index error, please try running ``aleph init``. Sorry for the inconvenience in setting this up!

**Comment by andkamau** [comment]
I think i've ran into this before, @danishthanvi1 
As @pudo says, try `evilshit` ... If that doesn't do the trick, try below (which is basically sequentially doing what `evilshit` does):

⚠️ Only do this if it's a fresh installation

1) Drop the DB:

```
dropdb aleph -U <user> -W -h <POSTGRES-HOST> -p 5432
```

2) Delete the ES index

```
curl -XDELETE "http://<ES-HOST>:9200/aleph"
```

3) Create the DB

```
createdb -E utf-8 -U <user> -W -h <POSTGRES-HOST> -p 5432
```

4) Create the ES index

```
curl -XPUT "http://<es-host>:9200/aleph"
```

5) `aleph upgrade`

**Comment by danishthanvi1** [comment]
Hi. 

Thanks for your Help, i have managed to Run Aleph it's working with Docker. 

One more issue iam facing for that iam opening a New Ticket.
