### ISSUE TITLE
when ingesting: application not registered on db instance and no application bound to current context

### ISSUE THREAD

**Issue by jbothma** [pudo/aleph#66]
[2016-08-10 16:01:14,345: INFO/MainProcess] Received task: aleph.ingest.ingest_url[4a99cc43-7025-40b1-b5dd-97e356df5811]
[2016-08-10 16:01:14,347: INFO/Worker-12] Ingesting URL: u'http://code4sa-gazettes.s3.amazonaws.com/archive/ZA-LP/2016/provincial-gazette-ZA-LP-vol-23-no-2731-dated-2016-07-08.pdf'
[2016-08-10 16:01:14,403: INFO/MainProcess] Received task: aleph.ingest.ingest_url[200a5e0c-6a13-4fd3-b7a1-7f64b4fc71bc]
[2016-08-10 16:01:14,484: ERROR/MainProcess] Task aleph.ingest.ingest_url[ba352afc-a713-476f-969f-dc1474121963] raised unexpected: RuntimeError('application not registered on db instance and no application bound to current context',)
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(_args, *_kwargs)
  File "/usr/local/lib/python2.7/site-packages/newrelic-2.46.0.37/newrelic/hooks/application_celery.py", line 66, in wrapper
    return wrapped(_args, *_kwargs)
  File "/usr/local/lib/python2.7/site-packages/celery/app/trace.py", line 438, in **protected_call**
    return self.run(_args, *_kwargs)
  File "/aleph/aleph/ingest/**init**.py", line 38, in ingest_url
    Ingestor.handle_exception(meta, collection_id, ex)
  File "/aleph/aleph/ingest/ingestor.py", line 57, in handle_exception
    db.session.rollback()
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/orm/scoping.py", line 157, in do
    return getattr(self.registry(), name)(_args, *_kwargs)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/util/_collections.py", line 990, in __call__
    return self.registry.setdefault(key, self.createfunc())
  File "/usr/local/lib/python2.7/site-packages/flask_sqlalchemy/**init**.py", line 771, in create_session
    return SignallingSession(self, **options)
  File "/usr/local/lib/python2.7/site-packages/flask_sqlalchemy/**init**.py", line 153, in **init**
    self.app = app = db.get_app()
  File "/usr/local/lib/python2.7/site-packages/flask_sqlalchemy/**init**.py", line 922, in get_app
    raise RuntimeError('application not registered on db '
RuntimeError: application not registered on db instance and no application bound to current context

**Comment by jbothma** [comment]
Seems to be triggered when the process processing the queue message is different from the one that inserted it into the queue or something like that, since it happens when after 20 tasks if I set CELERYD_MAX_TASKS_PER_CHILD  to 10 and run celery -c 2 or if I restart the worker docker container.
Is the message tied to the process somehow?

**Comment by longhotsummer** [comment]
Flask sets up a context with SQLAlchemy that stores the db session in what is essentially a threadlocal. It sounds like that context is missing for some reason. Different thread?

**Comment by pudo** [comment]
It's definitely not a "flask thread", so celery has to mock that up a little. I've seen this bug before, but don't recall how it was caused. My sense is that it may be incorrect error handling in a previous task, which then bleeds over and leaves an invalid context for successive tasks.

**Comment by pwalsh** [comment]
hey all.

I do not know what you have here, as i don't yet know the aleph code, but something sounds familiar to me, where I've had to explicitly pass around a flask app so it works with background processes (in my case, using `deferred` in AppEngine, but same thing). A small example code snippet:

```
def queueable_notification(*args, **kwargs):
    """Wraps a notification in callable that can be queued."""
    # We are operating outside Flask's normal app and request context,
    # so we need to get in new ones for all the functionality we require
    from main import app as app_instance
    with app_instance.app_context(), app.test_request_context():
        notification = Notification(*args, **kwargs)
        return notification
```

**Comment by pudo** [comment]
@jbothma can you post the *full* log of the worker? It'd be good to see previous exceptions and how they may have trashed the environment...

**Comment by jbothma** [comment]
[celery.log.zip](https://github.com/pudo/aleph/files/412721/celery.log.zip)

I'm not really sure at which points I restarted things but you cn probably roughly see it from the log. I think there were one or two occasions when I had multiple containers running concurrently which might have written to this file concurrently

**Comment by jbothma** [comment]
I don't want to force it now, but for me this seems to only happen when I restart a worker manually or via CELERYD_MAX_TASKS_PER_CHILD - in the ltter case perhaps context is kept around but because it's  new thread the context seems broken?

**Comment by pudo** [comment]
I’ve pushed 86f7c63d131924ee8e76a5707ae1c19167e2acbe which won't fix the issue but hopefully will allow us to see the underlying exception more clearly. Would you mind giving it a run?

**Comment by jbothma** [comment]
will do, as soon as the dockerhub build is done

**Comment by jbothma** [comment]
I was wrong about this happening necessarily when restrting workers - I just updated and restarted and they picked up jobs and continued ingesting and writing to db without these errors.

I'll now switch on CELERYD_MAX_TASKS_PER_CHILD again

**Comment by jbothma** [comment]
This just started again and seemed to be with a regenerated worker

```
[2016-08-11 11:27:06,538: INFO/Worker-2] Index document: <Document(278L,u'text',u'KwaZulu-Natal Provincial Gazette vol 9 no 1554 dated 20 November 2015')>
[2016-08-11 11:27:06,714: INFO/MainProcess] Task aleph.ingest.ingest_url[73fc380b-4f37-476d-a838-bad86e1b6546] succeeded in 114.484578229s: None
[2016-08-11 11:27:06,904: INFO/MainProcess] Received task: aleph.ingest.ingest_url[32f3d8f2-963f-4a79-9537-44c716020864]
[2016-08-11 11:27:07,239: INFO/Worker-3] New Relic Python Agent (2.46.0.37)
[2016-08-11 11:27:07,274: INFO/MainProcess] Received task: aleph.ingest.ingest_url[90222058-242a-4602-bd15-64e4b8fefaa2]
[2016-08-11 11:27:07,324: INFO/Worker-3] Ingesting URL: u'http://code4sa-gazettes.s3.amazonaws.com/archive/ZA/2014/government-gazette-ZA-vol-583-no-37246-dated-2014-01-24.pdf'
[2016-08-11 11:27:07,889: INFO/Worker-3] Traceback (most recent call last):
  File "/aleph/aleph/ingest/__init__.py", line 35, in ingest_url
    meta = get_archive().archive_file(tmp_path, meta, move=True)
  File "/aleph/aleph/core.py", line 118, in get_archive
    app = current_app._get_current_object()
  File "/usr/local/lib/python2.7/site-packages/werkzeug/local.py", line 302, in _get_current_object
    return self.__local()
  File "/usr/local/lib/python2.7/site-packages/flask/globals.py", line 51, in _find_app
    raise RuntimeError(_app_ctx_err_msg)
RuntimeError: Working outside of application context.

This typically means that you attempted to use functionality that needed
to interface with the current application object in a way.  To solve
this set up an application context with app.app_context().  See the
documentation for more information.

[2016-08-11 11:27:07,889: WARNING/Worker-3] Error ['RuntimeError']: Working outside of application context.

This typically means that you attempted to use functionality that needed
to interface with the current application object in a way.  To solve
this set up an application context with app.app_context().  See the
documentation for more information.
[2016-08-11 11:27:07,889: WARNING/Worker-3] [2016-08-11 11:27:07,889] ERROR in ingestor: Error storing crawler exception: RuntimeError('application not registered on db instance and no application bound to current context',)
[2016-08-11 11:27:07,905: WARNING/Worker-3] Traceback (most recent call last):
[2016-08-11 11:27:07,905: WARNING/Worker-3] File "/usr/local/lib/python2.7/logging/handlers.py", line 934, in emit
[2016-08-11 11:27:07,918: WARNING/Worker-3] ",".join(self.toaddrs),
[2016-08-11 11:27:07,919: WARNING/Worker-3] TypeError: sequence item 0: expected string, NoneType found
[2016-08-11 11:27:07,919: WARNING/Worker-3] Logged from file ingestor.py, line 78
[2016-08-11 11:27:07,889: ERROR/Worker-3] Error storing crawler exception: RuntimeError('application not registered on db instance and no application bound to current context',)
[2016-08-11 11:27:07,921: INFO/Worker-3] Ingesting URL: u'http://code4sa-gazettes.s3.amazonaws.com/archive/ZA/2012/tender-bulletin-ZA-vol-566-no-2739-dated-2012-08-10.pdf'
```

[celery.log2.txt](https://github.com/pudo/aleph/files/413066/celery.log2.txt)

**Comment by jbothma** [comment]
I think you're right @pwalsh - today I found the kernel killing workers running out of memory triggering this

this looks like our guy http://flask.pocoo.org/docs/dev/patterns/celery/

the key is that a new worker needs to get a new context because cycling workers is the only way to deal with the memory
http://stackoverflow.com/questions/26202713/celery-will-not-flush-memory-when-task-has-ended

**Comment by pwalsh** [comment]
@jbothma it was clear from the type of errors, but you all ignored me :), so I let it go :).

**Comment by pudo** [comment]
So I haven't been able to reproduce this bug in the past few months, and it appears some of it is also mitigated through the use of MAX_TASKS etc. So I'm closing this pending further discoveries.
