### ISSUE TITLE
elasticsearch NumberFormatexception

### ISSUE THREAD

**Issue by jbothma** [pudo/aleph#70]
```
[2016-08-14 01:40:58,055][DEBUG][action.search.type       ] [Karima Shapandar] All shards failed for phase: [query]
org.elasticsearch.search.SearchParseException: [aleph][4]: from[0],size[-1],sort[<custom:"updated_at": org.elasticsearch.index.fielddata.fieldcomparator.LongValuesComparatorSource@56acf987>!,<custom:"created_at": org.elasticsearch.index.fielddata.fieldcomparator.LongValuesComparatorSource@92f95dd>!,<score>]: Parse Failure [Failed to parse source [{"sort": [{"updated_at": "desc"}, {"created_at": "desc"}, "_score"], "from": 0, "_source": ["collection_id", "title", "file_name", "extension", "languages", "countries", "source_url", "created_at", "updated_at", "type", "summary", "source_collection_id"], "aggregations": {"entities": {"aggs": {"inner": {"filter": {"bool": {"must": [{"terms": {"entities.collection_id": [1, 9]}}]}}, "aggs": {"entities": {"terms": {"field": "entities.id", "size": 50}}}}}, "nested": {"path": "entities"}}, "scoped": {"global": {}, "aggs": {"collections": {"filter": {"query": {"filtered": {"filter": {"bool": {"must": [{"terms": {"collection_id": [1, 9]}}]}}, "query": {"match_all": {}}}}}, "aggs": {"collections": {"terms": {"field": "collection_id", "size": 1000}}}}}}}, "query": {"filtered": {"filter": {"bool": {"must": [{"terms": {"collection_id": [1, 9]}}, {"terms": {"collection_id": ["{{crawler.collection.id}}"]}}]}}, "query": {"match_all": {}}}}, "size": 20}]]
	at org.elasticsearch.search.SearchService.parseSource(SearchService.java:747)
	at org.elasticsearch.search.SearchService.createContext(SearchService.java:572)
	at org.elasticsearch.search.SearchService.createAndPutContext(SearchService.java:544)
	at org.elasticsearch.search.SearchService.executeQueryPhase(SearchService.java:306)
	at org.elasticsearch.search.action.SearchServiceTransportAction$5.call(SearchServiceTransportAction.java:231)
	at org.elasticsearch.search.action.SearchServiceTransportAction$5.call(SearchServiceTransportAction.java:228)
	at org.elasticsearch.search.action.SearchServiceTransportAction$23.run(SearchServiceTransportAction.java:559)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NumberFormatException: For input string: "{{crawler.collection.id}}"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:580)
	at java.lang.Integer.parseInt(Integer.java:615)
	at org.elasticsearch.index.mapper.core.IntegerFieldMapper.parseValue(IntegerFieldMapper.java:180)
	at org.elasticsearch.index.mapper.core.IntegerFieldMapper.indexedValueForSearch(IntegerFieldMapper.java:171)
	at org.elasticsearch.index.mapper.core.AbstractFieldMapper.termFilter(AbstractFieldMapper.java:469)
	at org.elasticsearch.index.mapper.core.NumberFieldMapper.termFilter(NumberFieldMapper.java:286)
	at org.elasticsearch.index.mapper.core.AbstractFieldMapper.termsFilter(AbstractFieldMapper.java:482)
	at org.elasticsearch.index.query.TermsFilterParser.parse(TermsFilterParser.java:202)
	at org.elasticsearch.index.query.QueryParseContext.executeFilterParser(QueryParseContext.java:373)
	at org.elasticsearch.index.query.QueryParseContext.parseInnerFilter(QueryParseContext.java:354)
	at org.elasticsearch.index.query.BoolFilterParser.parse(BoolFilterParser.java:92)
	at org.elasticsearch.index.query.QueryParseContext.executeFilterParser(QueryParseContext.java:373)
	at org.elasticsearch.index.query.QueryParseContext.parseInnerFilter(QueryParseContext.java:354)
	at org.elasticsearch.index.query.FilteredQueryParser.parse(FilteredQueryParser.java:74)
	at org.elasticsearch.index.query.QueryParseContext.parseInnerQuery(QueryParseContext.java:307)
	at org.elasticsearch.index.query.IndexQueryParserService.innerParse(IndexQueryParserService.java:382)
	at org.elasticsearch.index.query.IndexQueryParserService.parse(IndexQueryParserService.java:281)
	at org.elasticsearch.index.query.IndexQueryParserService.parse(IndexQueryParserService.java:276)
	at org.elasticsearch.search.query.QueryParseElement.parse(QueryParseElement.java:33)
	at org.elasticsearch.search.SearchService.parseSource(SearchService.java:731)
```

**Comment by pudo** [comment]
Can you give any further indications on the context of this? Seems to somehow be related to crawler collections in some obscure way, but it's not enough to build an actual idea of what's going on here.

**Comment by jbothma** [comment]
sorry, will try ASAP or close if it doesn't present any more

**Comment by jbothma** [comment]
hmmm I think this is fixed now.

`Caused by: java.lang.NumberFormatException: For input string: "{{crawler.collection.id}}"` suggests the collection ID wasn't being templated in during crawling but I've been doing a lot of indexing today and it's working fine.
