### ISSUE TITLE
Searching for `(36/2005): Explanatory Memorandum on` results in elasticsearch and API error 

### ISSUE THREAD

**Issue by jbothma** [pudo/aleph#88]
If `(36/2005): Explanatory Memorandum on` isn't vaid search syntax he UI should help the user with that.

ElasticSearch log:

```
[2016-09-13 14:15:38,514][DEBUG][action.search.type       ] [Karima Shapandar] [aleph][3], node[Ml_5uSyVRm-WGGSQBLVvGQ], [P], s[STARTED]: Failed to execute [org.elasticsearch.action.search.
SearchRequest@1d913641] lastShard [true]
org.elasticsearch.search.SearchParseException: [aleph][3]: from[0],size[-1]: Parse Failure [Failed to parse source [{"sort": ["_score"], "from": 0, "_source": ["collection_id", "title", "fi
le_name", "extension", "languages", "countries", "source_url", "created_at", "updated_at", "type", "summary", "source_collection_id"], "aggregations": {"entities": {"aggs": {"inner": {"filt
er": {"bool": {"must": [{"terms": {"entities.collection_id": [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]}}]}}, "aggs": {"entities": {"terms": {"field": "entities.id", "size": 50}}}}}, "nest
ed": {"path": "entities"}}, "scoped": {"global": {}, "aggs": {"collections": {"filter": {"query": {"filtered": {"filter": {"bool": {"must": [{"terms": {"collection_id": [1, 2, 3, 4, 5, 6, 7
, 8, 9, 10, 11, 12, 13]}}]}}, "query": {"bool": {"minimum_should_match": 1, "should": [{"query_string": {"use_dis_max": true, "query": "(36/2005): Explanatory Memorandum on", "default_opera
tor": "AND", "fields": ["title^15", "file_name", "summary^10", "title_latin^12", "summary_latin^8"]}}, {"has_child": {"query": {"bool": {"should": [{"query_string": {"use_dis_max": true, "q
uery": "(36/2005): Explanatory Memorandum on", "default_operator": "AND", "fields": ["text^6", "text_latin^2"]}}]}}, "type": "record"}}]}}}}}, "aggs": {"collections": {"terms": {"field": "c
ollection_id", "size": 1000}}}}}}}, "query": {"filtered": {"filter": {"bool": {"must": [{"terms": {"collection_id": [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]}}]}}, "query": {"bool": {"min
imum_should_match": 1, "should": [{"query_string": {"use_dis_max": true, "query": "(36/2005): Explanatory Memorandum on", "default_operator": "AND", "fields": ["title^15", "file_name", "sum
mary^10", "title_latin^12", "summary_latin^8"]}}, {"has_child": {"query": {"bool": {"should": [{"query_string": {"use_dis_max": true, "query": "(36/2005): Explanatory Memorandum on", "defau
lt_operator": "AND", "fields": ["text^6", "text_latin^2"]}}]}}, "type": "record"}}]}}}}, "size": 20}]]
        at org.elasticsearch.search.SearchService.parseSource(SearchService.java:747)
        at org.elasticsearch.search.SearchService.createContext(SearchService.java:572)
        at org.elasticsearch.search.SearchService.createAndPutContext(SearchService.java:544)
        at org.elasticsearch.search.SearchService.executeQueryPhase(SearchService.java:306)
        at org.elasticsearch.search.action.SearchServiceTransportAction$5.call(SearchServiceTransportAction.java:231)
        at org.elasticsearch.search.action.SearchServiceTransportAction$5.call(SearchServiceTransportAction.java:228)
        at org.elasticsearch.search.action.SearchServiceTransportAction$23.run(SearchServiceTransportAction.java:559)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: org.elasticsearch.index.query.QueryParsingException: [aleph] Failed to parse query [(36/2005): Explanatory Memorandum on]
        at org.elasticsearch.index.query.QueryStringQueryParser.parse(QueryStringQueryParser.java:250)
        at org.elasticsearch.index.query.QueryParseContext.parseInnerQuery(QueryParseContext.java:307)
        at org.elasticsearch.index.query.BoolQueryParser.parse(BoolQueryParser.java:107)
        at org.elasticsearch.index.query.QueryParseContext.parseInnerQuery(QueryParseContext.java:307)
        at org.elasticsearch.index.query.FilteredQueryParser.parse(FilteredQueryParser.java:71)
        at org.elasticsearch.index.query.QueryParseContext.parseInnerQuery(QueryParseContext.java:307)
        at org.elasticsearch.index.query.QueryFilterParser.parse(QueryFilterParser.java:47)
        at org.elasticsearch.index.query.QueryParseContext.executeFilterParser(QueryParseContext.java:373)
        at org.elasticsearch.index.query.QueryParseContext.parseInnerFilter(QueryParseContext.java:354)
        at org.elasticsearch.index.query.IndexQueryParserService.parseInnerFilter(IndexQueryParserService.java:295)
        at org.elasticsearch.search.aggregations.bucket.filter.FilterParser.parse(FilterParser.java:42)
        at org.elasticsearch.search.aggregations.AggregatorParsers.parseAggregators(AggregatorParsers.java:148)
        at org.elasticsearch.search.aggregations.AggregatorParsers.parseAggregators(AggregatorParsers.java:138)
```

**Comment by pudo** [comment]
I wonder if it'd make sense to follow up parse errors on queries by re-running the same query without ES query syntax enabled? (i.e. as a simplified MatchQuery)

**Comment by jbothma** [comment]
Sounds like a great solution. Instead of the frontend tryingto parse the
query and figure out whether es will understand or not
